services:
  mysql:
    container_name: mysql-server
    build:
      context: ./
      dockerfile: mysql/Dockerfile
    ports:
      - "3300:3306"
    networks:
      - app-network


  php:
    container_name: php-server
    build:
      context: ./
      dockerfile: php/Dockerfile
    volumes:
      - ./app:/var/www/html 
    networks:
      - app-network
    depends_on:
      - mysql


  ngnix:
    container_name: nginx-server
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - php




networks:
  app-network:
    driver: bridge
