services:
  mysql:
    container_name: mysql-server
    build:
      context: ./docker
      dockerfile: Dockerfile.mysql
    networks:
      - app-network


  php:
    container_name: php-server
    build:
      context: ./docker
      dockerfile: Dockerfile.php
    networks:
      - app-network
    depends_on:
      - mysql


  ngnix:
    container_name: nginx-server
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - php



networks:
  app-network:
    driver: bridge
