services:
  mysql:
    container_name: mysql-server
    build:
      context: ./
      dockerfile: mysql/Dockerfile
    networks:
      - app-network


  php:
    container_name: php-server
    build:
      context: ./
      dockerfile: php/Dockerfile
    networks:
      - app-network
    depends_on:
      - mysql


  ngnix:
    container_name: nginx-server
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - php



networks:
  app-network:
    driver: bridge
