services:
  php:
    container_name: php-container
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./app:/var/www/html 
    ports:
      - "9000:8000"
    networks:
      - app-network

  ngnix:
    container_name: nginx-server
    image: nginx:alpine
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - php

networks:
  app-network:
    driver: bridge
