<?php

require_once './vendor/autoload.php';







// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX
// TODO FAZER USUÀRIO, EMAIL, MAILBOX